apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
  - name: honcho-ui-html
    namespace: honcho
    files:
      - index.html
  - name: honcho-ui-nginx
    namespace: honcho
    files:
      - nginx.conf
generatorOptions:
  disableNameSuffixHash: true
