apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hermes-rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: git@github.com:bmobytes/bartos-cloud-gitops.git
    targetRevision: main
    path: apps/infrastructure/hermes-rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: hermes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
