apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: netdata
  source:
    repoURL: git@github.com:bmobytes/bartos-cloud-gitops.git
    targetRevision: main
    path: apps/secrets/netdata
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
