apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-application.yaml
  - metallb-config-application.yaml
  - longhorn-application.yaml
  - ingress-nginx-application.yaml
  - cert-manager-application.yaml
  - cert-manager-issuers-application.yaml
  - hermes-rbac-application.yaml
  - netdata-application.yaml
  - infisical-operator-application.yaml
  - infisical-secrets-application.yaml
  - external-dns-secrets-application.yaml
  - external-dns-application.yaml
  - honcho-db-secrets-application.yaml
  - honcho-postgres-application.yaml
  - honcho-secrets-application.yaml
  - honcho-application.yaml
  - honcho-ui-application.yaml
  - firecrawl-secrets-application.yaml
  - firecrawl-application.yaml
  - openlit-application.yaml
  - open-webui-secrets-application.yaml
  - open-webui-application.yaml
