apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-application.yaml
  - cert-manager-issuers-application.yaml
  - external-dns-application.yaml
  - hermes-rbac-application.yaml
  - netdata-application.yaml
  - infisical-operator-application.yaml
  - infisical-secrets-application.yaml
  - honcho-postgres-application.yaml
  - honcho-secrets-application.yaml
  - honcho-application.yaml
  - honcho-ui-application.yaml
