apiVersion: v1
kind: ConfigMap
metadata:
  name: firecrawl-playwright-config
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
data:
  MAX_CONCURRENT_PAGES: {{ .Values.playwright.maxConcurrentPages | quote }}
  ALLOW_LOCAL_WEBHOOKS: "true"
  BLOCK_MEDIA: "true"
