apiVersion: v1
kind: Service
metadata:
  name: firecrawl-playwright
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
    app.kubernetes.io/name: firecrawl-playwright
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: firecrawl-playwright
    app.kubernetes.io/part-of: firecrawl
  ports:
    - port: {{ .Values.playwright.port }}
      targetPort: http
      protocol: TCP
      name: http
