apiVersion: v1
kind: Service
metadata:
  name: firecrawl-rabbitmq
  labels:
    {{- include "firecrawl.labels" . | nindent 4 }}
    app.kubernetes.io/name: firecrawl-rabbitmq
    app.kubernetes.io/component: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rabbitmq.port }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app.kubernetes.io/name: firecrawl-rabbitmq
    app.kubernetes.io/part-of: firecrawl
