apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: external-dns-credentials-claim
  namespace: external-dns
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    resyncInterval: 60s
    instantUpdates: false
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: bartos-k8s-6-lmc
        envSlug: prod
        secretsPath: "/external-dns"
        recursive: false
      credentialsRef:
        secretName: universal-auth-credentials
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: technitium-credentials
      secretNamespace: external-dns
      creationPolicy: Owner
