apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: netdata-cloud-claim
  namespace: netdata
spec:
  hostAPI: https://app.infisical.com/api
  syncConfig:
    resyncInterval: 60s
    instantUpdates: false
  authentication:
    kubernetesAuth:
      identityId: f3addf26-3518-489f-8c87-1e55862b1ece
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: infisical-auth
        namespace: infisical
      secretsScope:
        projectSlug: bartos-k8s-6-lmc
        envSlug: prod
        secretsPath: "/"
        recursive: false
  managedKubeSecretReferences:
    - secretName: netdata-cloud-claim
      secretNamespace: netdata
      creationPolicy: Owner
