apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: honcho-postgres-data
  namespace: honcho
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
